import Head from 'next/head'
import styles from '../styles/Layout.module.css'

export default function Layout({ children }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Metacodya</title>
        <meta name="description" content="Generated by Metacodya" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <span>Metacodya</span>
      </header>

      <main className={styles.main}>{children}</main>
    </div>
  )
}
